### ISSUE TITLE
HtmlProcessingInstruction type missing

### ISSUE THREAD

**Issue by eliotwrobson** [abelcheung/types-lxml#28]
See title. There's no type annotation for HtmlProcessingInstruction (just a comment here: https://github.com/abelcheung/types-lxml/blob/main/lxml-stubs/html/_element.pyi#L228).

This class seems to be supported by lxml, and the project I'm working on uses this in our test cases (see https://github.com/PrairieLearn/PrairieLearn/pull/9356#discussion_r1474979010). I think the annotation for this should be added back to the stubs here.

**Comment by abelcheung** [comment]
It's fine for me, just that I'm **really** surprised it's actually been used. Will create a release after this change.
