### ISSUE TITLE
Avoid non-public classes in the type declarations

### ISSUE THREAD

**Issue by scoder** [abelcheung/types-lxml#31]
lxml's author here. I've been following the development of type annotation packages for lxml, and it seems a general difficulty to express the interface of objects returned from the API functions that generate or select XML trees and elements. Users of these annotation packages end up importing non-public classes from lxml's modules, such as `_Element`. This is generally frowned upon as bad style and is usually also rejected by code checkers.

I personally think that  [Protocols](https://typing.readthedocs.io/en/latest/spec/protocol.html) can solve this. I think a set of protocols is really what lxml's element API is, it's a bunch of objects and classes that implement a common or slightly different interface. It's usually not relevant what their inheritance relationship is, all that really matters is their specific interface. Thus, they seem best represented as protocols.

Could `types-lxml` switch to representing and declaring elements as protocols?

**Comment by abelcheung** [comment]
1. The cat is already out of bag for too many years. I suppose too many real world code are already using `isinstance()`, `issubclass()` etc to check against elements. Placing a big change like this can be disruptive to existing user base, and I guess you don't want that yourself. 

2. Nominal typing is already too hardwired into the stub package. Switching to Protocol perhaps need a codebase written from scratch, and test out if the idea really works. It's not something done with just a few patches.

3. Protocol probably doesn't solve all problems with existing lxml api. A prominent example is that protocols and method overloads don't play nicely with each other. And there are some incompatible class overrides to be reckoned (such as subclass containing readonly attributes when base class one is read-write)

My take is that it requires another code base, and experiment would likely fail.
