### ISSUE TITLE
Return type for _Attrib.get() and .pop()

### ISSUE THREAD

**Issue by wRAR** [abelcheung/types-lxml#6]
Currently the `lxml.etree._Attrib` stub is like this:

```
    # Signature is pop(self, key, *default), yet followed by runtime
    # check and raise exception if multiple default argument is supplied
    @overload
    def pop(self, key: _AttrName) -> str | None: ...
    @overload
    def pop(self, key: _AttrName, default: _T) -> str | _T: ...
[...]
    def __getitem__(self, __k: _AttrName) -> str: ...
[...]
    @overload
    def get(self, key: _AttrName) -> str | None: ...
    @overload
    def get(self, key: _AttrName, default: _T) -> str | _T: ...
```

I'm looking at the current lxml code and I think all these methods never return None, raising KeyError instead, so it makes sense to me to change both `pop()` and `get()` to match `__getitem__()` and return `str` when the default is not provided. What do you think?

**Comment by abelcheung** [comment]
@wRAR Sorry for late reply. It seems the story is a bit more complex than either you or me have thought.

```pycon
In [15]: import lxml
In [16]: lxml.__version__
Out[16]: '4.9.1'

In [17]: import lxml.html
In [18]: root = lxml.html.fragment_fromstring('<input type="checkbox" checked>')
In [19]: root.attrib
Out[19]: {'type': 'checkbox', 'checked': 'checked'}

In [20]: y = root.attrib.get('foobar')
In [21]: type(y)
Out[21]: <class 'NoneType'>

In [22]: y = root.attrib.pop('xxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\lxml\etree.pyx", line 2466, in lxml.etree._Attrib.pop
KeyError: 'xxx'

'xxx'
```

I haven't checked earlier versions of lxml, but for simplicity I'll follow the behavior of newest version for now -- you're correct that `_Attrib.pop()` needs fixing.

**Comment by wRAR** [comment]
Indeed, I've looked at the code again and now I see that `get()` can return None. Maybe I've confused it with `__getitem__()`, which throws.
Thanks!
