### ISSUE TITLE
Required baseurl in fromstring()

### ISSUE THREAD

**Issue by wRAR** [abelcheung/types-lxml#7]
As far as I can see, `lxml.etree.fromstring()` doesn't really require `base_url`, so this overload looks too strict:

```
@overload
def fromstring(
    text: _AnyStr,
    parser: _DefEtreeParsers[_T_co],
    *,
    base_url: _AnyStr = ...,
) -> _T_co: ...
```

E.g. https://lxml.de/tutorial.html#event-driven-parsing has examples of passing `text` and `parser` but not `base_url`.

**Comment by abelcheung** [comment]
Although website doesn't show example of `base_url` argument, it is available [in source code](https://github.com/lxml/lxml/blob/77413c28e237f3f4bf2363150aaab9d2f7705f7b/src/lxml/etree.pyx#L3242-L3254) as optional keyword argument. The usage of ellipsis marks it as optional, so it indeed isn't strictly needed. Is there any issue?

**Comment by wRAR** [comment]
Hmm, I think I meant that it's _AnyStr, not Optional[_AnyStr]? I'll check the actual problem later.

**Comment by wRAR** [comment]
Yes, the mypy output is 

`error: Argument "base_url" to "fromstring" has incompatible type "Optional[str]"; expected "Union[str, bytes]"`

**Comment by abelcheung** [comment]
Silly me, the correct `base_url` type was already all over the places, yet I got it wrong for `fromstring()`. I certainly need more caffeine doses 😏 OK, to be serious, tests for `lxml.etree` proper need some love.
